### ISSUE TITLE
input name in onnxruntime is hardcoded in README

### ISSUE THREAD

**Issue by londumas** [fumihwh/onnx-pytorch#30]
https://github.com/fumihwh/onnx-pytorch/blob/29cd1dafb47e4e4bc598c700c44f53815e7b8c9a/README.md?plain=1#L87

I would suggest changing the following line
```
inputs = {"data": inp}
```

to this one, in the README
```
inputs = {session.get_inputs()[0].name: inp}
```

This allows to adapt to a way larger variety of model, without hardcoding the input name.

**Comment by fumihwh** [comment]
@londumas 
Sure, I'm open to this. 
The input name `data` is strong binding to the test model `resnet18-v2-7.onnx`. If one follows the tutorial, `data` will be good enough. But for the robustness, change to `session.get_inputs()[0].name` sounds good for me.
