### ISSUE TITLE
change directory is missing

### ISSUE THREAD

**Issue by londumas** [fumihwh/onnx-pytorch#31]
https://github.com/fumihwh/onnx-pytorch/blob/29cd1dafb47e4e4bc598c700c44f53815e7b8c9a/README.md?plain=1#L19

the command line block should be
```
git clone https://github.com/fumihwh/onnx-pytorch.git
cd onnx-pytorch
pip install -r requirements.txt
pip install -e .
```

**Comment by fumihwh** [comment]
Fixed! Thanks!
